name: Kernel Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Isse agar third-party actions abhi Node 20 par hi hain toh build fail nahi hoga
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: 'true'

    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v5

    - name: Set up MemKernel as a module (M-OUT) with specified name
      run: |
        curl -LSs "https://raw.githubusercontent.com/Poko-Apps/MemKernel/main/kernel/setup.sh" | bash -s M

    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        NAME: Loganysl
      with:
        arch: arm64
        compiler: gcc/12
        defconfig: blossom_defconfig
        image: Image.gz

    - name: Upload Kernel and Module
      uses: actions/upload-artifact@v5
      with:
        name: moduleandkernel
        path: |
          ${{ steps.build.outputs.outfile }}
          ./out/drivers/memkernel/memkernel.ko
