name: Kernel Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: 'true'

    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v5

    - name: Set up MemKernel directly into Kernel (Inbuilt - Y)
      run: |
        curl -LSs "https://raw.githubusercontent.com/Poko-Apps/MemKernel/main/kernel/setup.sh" | bash -s Y Loganysl

    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        NAME: Loganysl
      with:
        arch: arm64
        compiler: clang/14
        defconfig: blossom_defconfig
        image: Image.gz

    - name: Upload Built Kernel Image
      uses: actions/upload-artifact@v6
      with:
        name: Inbuilt_MemKernel_Image
        path: ${{ steps.build.outputs.outfile }}
