name: Kernel Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: 'true'

    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v5

    - name: Integrate KernelSU Next
      run: |
        curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -

    - name: Set up MemKernel directly into Kernel (Inbuilt)
      run: |
        curl -LSs "https://raw.githubusercontent.com/Poko-Apps/MemKernel/main/kernel/setup.sh" | bash -s Y Loganysl

    - name: Force Enable Drivers in Defconfig
      run: |
        find . -name "blossom_defconfig" -exec sh -c '
          echo "CONFIG_KSU=y" >> "{}"
          echo "CONFIG_MEMKERNEL=y" >> "{}"
        ' \;

    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        NAME: Loganysl
      with:
        arch: arm64
        compiler: clang/14
        defconfig: blossom_defconfig
        image: Image.gz

    - name: Upload Built Kernel Image
      uses: actions/upload-artifact@v6
      with:
        name: KSU_MemKernel_Image
        path: ${{ steps.build.outputs.outfile }}
